### ISSUE TITLE
hello can you please help i am stuck at a issue.

### ISSUE THREAD

**Issue by smritifotedar** [ShivamJoker/InShare#2]

**Comment by smritifotedar** [comment]
index.js:51 POST https://innshare.herokuapp.comapi/files net::ERR_NAME_NOT_RESOLVED
uploadFile @ index.js:51
(anonymous) @ index.js:27
![Screenshot (191)](https://user-images.githubusercontent.com/73025731/103657532-07d1b180-4f90-11eb-970a-37784ff7d423.png)

**Comment by Ritika-Das** [comment]
> index.js:51 POST https://innshare.herokuapp.comapi/files net::ERR_NAME_NOT_RESOLVED
> uploadFile @ index.js:51
> (anonymous) @ index.js:27
> ![Screenshot (191)](https://user-images.githubusercontent.com/73025731/103657532-07d1b180-4f90-11eb-970a-37784ff7d423.png)

Please recheck if your uploadURL is as such <code>const uploadURL = `${baseURL}/api/files`;</code> because the / symbol after .com is missing.

**Comment by smritifotedar** [comment]
i
![Screenshot (193)](https://user-images.githubusercontent.com/73025731/103663118-c264b280-4f96-11eb-9456-c54dec002a25.png)
![Screenshot (194)](https://user-images.githubusercontent.com/73025731/103663125-c42e7600-4f96-11eb-92cb-585f7f172cb0.png)
![Screenshot (195)](https://user-images.githubusercontent.com/73025731/103663137-c5f83980-4f96-11eb-905a-9cb3b5b753a8.png)
![Screenshot (196)](https://user-images.githubusercontent.com/73025731/103663143-c5f83980-4f96-11eb-9dc8-25b69def46f5.png)
please look

**Comment by smritifotedar** [comment]
@ShivamJoker @Ritika-Das please look
