### ISSUE TITLE
plpease look

### ISSUE THREAD

**Issue by smritifotedar** [ShivamJoker/InShare#3]
Access to XMLHttpRequest at 'https://innshare.herokuapp.com/api/files' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index.js:47 
index.js:51 POST https://innshare.herokuapp.com/api/files net::ERR_FAILED
uploadFile @ index.js:51
(anonymous) @ index.js:27

**Comment by ShivamJoker** [comment]
First of all please stop spamming the repo and try to do some research instead of just opening issues.
You should use localhost:3000 instead of the IP
