### ISSUE TITLE
Not able to run the code on local environment

### ISSUE THREAD

**Issue by yogi2103** [ShivamJoker/InShare#6]
When I'm opening the html file and uploading the file then it doesn't upload and show xhr status 0. Could you please help me with this?

**Comment by ShivamJoker** [comment]
Can you please open the console and paste the error here ?

**Comment by yogi2103** [comment]
![Screenshot (197)](https://user-images.githubusercontent.com/57219370/126069871-44140544-5450-4929-9ec4-51689c495037.png)
![Screenshot (198)](https://user-images.githubusercontent.com/57219370/126070767-04b7ae6d-bc5d-4bdf-85b9-b0ca63af3ee2.png)

**Comment by yogi2103** [comment]
@ShivamJoker Could you please look into this?

**Comment by ShivamJoker** [comment]
@yogi2103 please run it with a local server on port 5500

**Comment by yogi2103** [comment]
Hi @ShivamJoker I even tried to use your site https://send.creativeshi.com/ which is also giving me same error. Could you please have a look into this?

![Screenshot (203)](https://user-images.githubusercontent.com/57219370/126889333-34413de5-49a9-457f-a0ef-5b0da7898a42.png)
